apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: emartapp-DEV
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
      - name: mongo
        image: mongo:4

        ports:
        - containerPort: 27017

        env:
        - name: MONGO_INITDB_DATABASE
          value: epoc

        volumeMounts:
        - name: mongo-init-volume
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: mongo-init-volume
        configMap:
          name: mongo-init-script