apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: emartapp-qa
  labels:
    environment: DEV
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: emartdbpass-qa
  DB_USERNAME: root