apiVersion: v1
kind: Service
metadata:
  name: emongo
  namespace: emartapp-qa
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    app: mongo

  ports:
  - port: 27017
    targetPort: 27017

  type: ClusterIP