apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nginx
  namespace: argocd
spec: 
  destination: 
    namespace: emartapp-application
    server: "https://kubernetes.default.svc"
  project: helmk8s-project
  
  source: 
    path: Kubernetes_Manifest_Files/01-Frontend/01-NGINX_Service
    repoURL: "https://github.com/cloudchaps/ARGOCD_Repository.git"
    targetRevision: main
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true