apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapi-service
  namespace: emartapp-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapi-service
  template:
    metadata:
      labels:
        app: javaapi-service
    spec:
      containers:
      - name: javaapi-service
        image: darosa87/emartappjavaapi:1.0.3
        ports:
        - containerPort: 9000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_HOST

          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: DB_PORT

          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_DATABASE

          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: DB_USERNAME

          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD