apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: emartapp-qa 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  MYSQL_DATABASE: books
  DB_HOST: emartdb
  DB_PORT: "3306"