apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.appname }}

  template:
    metadata:
      labels:
        app: {{ .Values.appname }}

    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 80

        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config