apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: mongodb2
  namespace: argocd
spec: 
  destination: 
    namespace: emartapp-application
    server: "https://ED696E7589BA7CA7C3378A23EDAD6B2D.gr7.us-east-1.eks.amazonaws.com"
  project: default
  
  source: 
    path: Kubernetes_Manifest_Files/02-Backend/QA/01-MONGODB
    repoURL: "https://github.com/cloudchaps/ARGOCD_Repository.git"
    targetRevision: main
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true