apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: emartapp-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: darosa87/cloudchaps:1.0
        ports:
        - containerPort: 4200
