apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nodejsapiclient
  namespace: argocd
spec: 
  destination: 
    namespace: emartapp-application
    server: "https://kubernetes.default.svc"
  project: default
  
  source: 
    path: Kubernetes_Manifest_Files/01-Frontend/DEV/03-NodeJS_API
    repoURL: "https://github.com/cloudchaps/ARGOCD_Repository.git"
    targetRevision: main
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true