apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: emartapp-application
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location / {
          return 200 "Hello from Kubernetes NGINX!\n";
        }

        location /health {
          return 200 "OK\n";
        }
      }
    }